import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* Meta tag for viewport scaling */}
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <html lang="en">
        <body className={`${inter.className} max-w-full mx-auto my-8 sm:my-12 md:my-16 p-4 sm:p-6 md:p-8`}>
          {children}
        </body>
      </html>
    </>
  );
}
